---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
        - name: vproapp
          image: suhebghare/vpapp:v1
          ports:
            - name: vproapp-port
              containerPort: 8080
      initContainers:
        - name: init-mysql
          image: busybox
          commands: ['sh', '-c', 'until nslookup vprodb; do echo waiting for mydb; sleep 2; done;']
        - name: init-memcache
          image: busybox
          commands: [ 'sh', '-c', 'until nslookup vprocache01; do echo waiting for memcached; sleep 2; done;']
---
kind: Service
apiVersion: v1
metadata:
  name: vproapp
spec:
  ports:
    - port: 80
      targetPort: vproapp-port
      protocol: TCP
  selector:
    app: vproapp
  type: LoadBalancer